name: Deploy UserGuide

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy userguide to doc.mybroodminder.com
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 1150
        command_timeout: 120m
        script: |
          cd /mellisphera/production/userguide/
          git pull origin master &>> github_CD_output.txt
          git submodule foreach git pull origin master &>> github_CD_output.txt
          sudo /bin/sh build.sh &>> github_CD_output.txt
        
